### ISSUE TITLE
Makeswap errors out on invalid ToStartTime

### ISSUE THREAD

**Issue by Arkivix** [FUSIONFoundation/myfusionwallet#1]
@JoeyKhd 

https://github.com/FUSIONFoundation/myfusionwallet/blob/42c732fba2502714be9b1e4702448cfff2b4e28e/app/scripts/controllers/ensCtrl.js#L1296

The ToStartTime needs to be a hexadecimal string otherwise the backend will error,

**Comment by JoeyKhd** [comment]
Fixed in last commit.
