### ISSUE TITLE
Are you a scam??? more than 5 hours ago i sent tokens to your swap wallet but i still not get it back!

### ISSUE THREAD

**Issue by nastyatimosha** [FUSIONFoundation/myfusionwallet#72]
Are you a scam??? more than 5 hours ago i sent tokens to your swap wallet but i still not get it back!  and nobody answer your support messages! nobody to who speak or fix this! 

more than 5 hours ago i sent the tokens to your wallet! all correct.. from metamask.. before sent big amount i sent little amounts and all was good! but in the big amount i just didnt get back my tokens!! 

i dont want to think that you are a SCAM! but for now i am writing a report to COINMARKETCAP, COINGECKO AND COINPAPRIKA!

also i will post some screenshots in reddit and crypto forums as Bitcointalk.. this is just to people see what they can expect when buying your coins! i need my money!!!

https://blocks.fusionnetwork.io/#!/address/0x8647900169eed457d0cf7a02d6e4d58af13db06e

#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Versions
[NPM, Node, Web3.js, OS, device...]

**Comment by guggsverus** [comment]
I've seen your issue is resolved. Please delete this unfair post.
